import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import Providers from './providers';
import './globals.css';
import { getServerSession } from '@/lib/session';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession();

    return (
        <>
            <html lang="en">
                <Providers session={session}>
                    <body className={inter.className}>{children}</body>
                    <Toaster richColors />
                </Providers>
            </html>
        </>
    );
}
